package edu.scripps.yates.pcomplex;

public enum DistanceMeasure {
	PEARSON_CORRELATION_COEFFICIENT, //
	CORRELATION_PVALUE, //
	EUCLIDEAN_DISTANCE, //
	PEAK_LOCATION, //
	COAPEX_SCORE, //
	JACCARD_SCORE, //
	// BAYES_CORRELATION, //
	PEARSON_CORRELATION_COEFFICIENT_PLUS_NOISE, //
	WEIGTHED_CROSS_CORRELATION, //
	MUTUAL_INFORMATION, //
	APEX_SCORE
}
